version: '3.8'
## Services
services:

  ## PHP
  php:
    container_name: sample_php
    build:
      context: ./php
      dockerfile: Dockerfile
    env_file:
      - ./env/laravel.env
      - ./env/laraveldb.env
    volumes:
      - ./src:/var/www/html
    configs:
      - source: phplocal
        target: /usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    # volumes:
    #   - ./certs:/usr/local/share/ca-certificates
    networks:
      - sample_network

  ## MSSQL
  mssql:
    container_name: sample_mssql
    build:
      context: ./mssql
      dockerfile: Dockerfile
    user: root
    restart: unless-stopped
    tty: true
    ports:
      - "8433:1433"
    env_file:
      - ./env/sqlserver.env
      - ./env/sapassword.env
    volumes: 
      # - mssqlbackup:/var/opt/mssql/backup
      - ./mssql/backup:/var/opt/mssql/backup
      - mssqldata:/var/opt/mssql/data
      - mssqllog:/var/opt/mssql/log
      - mssqldump:/var/opt/mssql/dump
      # - ./certs:/usr/local/share/ca-certificates
    networks:
      - sample_network
      
  ## NGINX
  nginx:
    container_name: sample_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./src:/var/www/html
      # - ./certs:/usr/local/share/ca-certificates
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mssql
    networks:
      - sample_network

## Docker Configs
configs:
  nginx:
    file: ./nginx/default.conf
  phplocal:
    file: ./php/local.ini

## Docker Networks
networks:
  sample_network:
    driver: bridge
    name: sample_network

## Docker Volumes
volumes:
  mssqlbackup:
  mssqldata:
  mssqllog:
  mssqldump: